# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               El Niño
tagline:             'Algorithms to Fight Climate Change'
description:         ''
baseurl:             ''
paginate:            10

# Custom vars
google_analytics:    UA-106923899-1
plugins:             [jekyll-paginate]
# version:           1.0.0
