# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               El Niño
tagline:             'Using Algorithms to Fight Climate Change'
baseurl:             ''
paginate:            10

# Custom vars
# version:           1.0.0
